name: 'Activate Hermit'
description: 'Activate a Hermit environment'
inputs:
  working-directory:
    description: 'The directory with the Hermit environment (contains `bin/hermit`)'
    required: false
    default: './'
  cache:
    description: 'If "true", installed Hermit packages will be cached.'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - if: ${{ inputs.cache == 'true' }}
      id: bin-hash
      shell: bash
      run: |
        hash="$(find ./${{ inputs.working-directory }}/bin ! -type d | sort | xargs openssl sha256 | openssl sha256 -r | cut -d' ' -f1)"
        echo "hash=$hash" >> "$GITHUB_OUTPUT"
    - if: ${{ inputs.cache == 'true' }}
      uses: actions/cache@v4
      with:
        path: ${{ runner.os == 'macOS' && '~/Library/Caches/hermit/pkg' || '~/.cache/hermit/pkg' }}
        key: ${{ runner.os }}-${{ runner.arch}}-hermit-cache-${{ steps.bin-hash.outputs.hash }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch}}-hermit-cache-
    - shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ./bin/hermit env --raw >> "$GITHUB_ENV"
