name: build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - run: bin/hermit info node --json | jq -r '.[0].Reference.Channel' > .node-version
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: .node-version

      - run: npm clean-install

      - if: github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update `dist`
          file_pattern: dist/
